random: Use HK_FLAG_TIMER instead of HK_TYPE_TIMER
HK_TYPE_TIMER is an upstreamed version of HK_FLAG_TIMER that uses single
feature type. Use the downstream enum variable to fix the following
compilation error:

../drivers/char/random.c:1115:50: error: use of undeclared identifier 'HK_TYPE_TIMER'; did you mean 'HK_FLAG_TIMER'?
                        cpumask_and(&timer_cpus, housekeeping_cpumask(HK_TYPE_TIMER), cpu_online_mask);
                                                                      ^~~~~~~~~~~~~
                                                                      HK_FLAG_TIMER
../include/linux/sched/isolation.h:9:2: note: 'HK_FLAG_TIMER' declared here
        HK_FLAG_TIMER           = 1,
        ^

Fixes: dcf1ca8c9cf ("random: spread out jitter callback to different CPUs")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>