fs: ntfs3: Remove bitmap_size function
Log:
In file included from ../include/vdso/const.h:5,
                 from ../include/linux/const.h:4,
                 from ../include/linux/list.h:8,
                 from ../include/linux/wait.h:7,
                 from ../include/linux/wait_bit.h:8,
                 from ../include/linux/fs.h:6,
                 from ../fs/ntfs3/attrib.c:9:
../fs/ntfs3/ntfs_fs.h:948:41: error: expected ')' before 'bits'
  948 | static inline size_t bitmap_size(size_t bits)
      |                                         ^~~~
../include/uapi/linux/const.h:32:44: note: in definition of macro '__ALIGN_KERNEL_MASK'
   32 | #define __ALIGN_KERNEL_MASK(x, mask)    (((x) + (mask)) & ~(mask))
      |                                            ^
../include/linux/kernel.h:33:33: note: in expansion of macro '__ALIGN_KERNEL'
   33 | #define ALIGN(x, a)             __ALIGN_KERNEL((x), (a))
      |                                 ^~~~~~~~~~~~~~
../include/linux/bitmap.h:219:35: note: in expansion of macro 'ALIGN'
  219 | #define bitmap_size(nbits)      ((ALIGN(nbits, BITS_PER_LONG) / BITS_PER_BYTE))
      |                                   ^~~~~
../fs/ntfs3/ntfs_fs.h:948:22: note: in expansion of macro 'bitmap_size'
  948 | static inline size_t bitmap_size(size_t bits)
      |                      ^~~~~~~~~~~
../include/uapi/linux/const.h:32:47: error: expected ')' before '+' token
   32 | #define __ALIGN_KERNEL_MASK(x, mask)    (((x) + (mask)) & ~(mask))
      |                                               ^
../include/uapi/linux/const.h:31:41: note: in expansion of macro '__ALIGN_KERNEL_MASK'
   31 | #define __ALIGN_KERNEL(x, a)            __ALIGN_KERNEL_MASK(x, (typeof(x))(a) - 1)
      |                                         ^~~~~~~~~~~~~~~~~~~
../include/linux/kernel.h:33:33: note: in expansion of macro '__ALIGN_KERNEL'
   33 | #define ALIGN(x, a)             __ALIGN_KERNEL((x), (a))
      |                                 ^~~~~~~~~~~~~~
../include/linux/bitmap.h:219:35: note: in expansion of macro 'ALIGN'
  219 | #define bitmap_size(nbits)      ((ALIGN(nbits, BITS_PER_LONG) / BITS_PER_BYTE))
      |                                   ^~~~~
../fs/ntfs3/ntfs_fs.h:948:22: note: in expansion of macro 'bitmap_size'
  948 | static inline size_t bitmap_size(size_t bits)
      |                      ^~~~~~~~~~~
../include/uapi/linux/const.h:32:57: error: expected ')' before '&' token
   32 | #define __ALIGN_KERNEL_MASK(x, mask)    (((x) + (mask)) & ~(mask))
      |                                                         ^
../include/uapi/linux/const.h:31:41: note: in expansion of macro '__ALIGN_KERNEL_MASK'
   31 | #define __ALIGN_KERNEL(x, a)            __ALIGN_KERNEL_MASK(x, (typeof(x))(a) - 1)
      |                                         ^~~~~~~~~~~~~~~~~~~
../include/linux/kernel.h:33:33: note: in expansion of macro '__ALIGN_KERNEL'
   33 | #define ALIGN(x, a)             __ALIGN_KERNEL((x), (a))
      |                                 ^~~~~~~~~~~~~~
../include/linux/bitmap.h:219:35: note: in expansion of macro 'ALIGN'
  219 | #define bitmap_size(nbits)      ((ALIGN(nbits, BITS_PER_LONG) / BITS_PER_BYTE))
      |                                   ^~~~~
../fs/ntfs3/ntfs_fs.h:948:22: note: in expansion of macro 'bitmap_size'
  948 | static inline size_t bitmap_size(size_t bits)
      |                      ^~~~~~~~~~~

Fix: 463074c0812 ("bitmap: introduce generic optimized bitmap_size()")
Change-Id: c7afd3d5c99ce5a3c7ec53afb3736fa2f073c665
Signed-off-by: TogoFire <togofire@mailfence.com>