sched/fair: Add missing argument to function call
../kernel/sched/fair.c:143:37: error: too few arguments to function call, expected 2, have 1
  143 |         return -arch_scale_cpu_capacity(cpu);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~    ^
../include/linux/arch_topology.h:21:15: note: 'topology_get_cpu_scale' declared here
   21 | unsigned long topology_get_cpu_scale(struct sched_domain *sd, int cpu)
      |               ^                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.